apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adventofcode-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: adventofcode
      labels:
        app: adventofcode
    spec:
      containers:
        - name: adventofcode
          image: mfbieber/adventofcode
          ports:
            - name: aoc-port
              containerPort: 8080
