apiVersion: v1
kind: Pod
metadata:
  name: adventofcode
  labels:
    app: adventofcode
spec:
  containers:
    - name: adventofcode
      image: mfbieber/adventofcode
      ports:
        - name: aoc-port
          containerPort: 8080
