apiVersion: v1
kind: ReplicationController
metadata:
  name: adventofcode-controller
spec:
  replicas: 2
  selector:
    app: adventofcode
  template:
    metadata:
      name: adventofcode
      labels:
        app: adventofcode
    spec:
      containers:
        - name: adventofcode
          image: mfbieber/adventofcode
          ports:
            - name: aoc-port
              containerPort: 8080
